{{- if and .Values.simulink.enabled .Values.simulink.interactive }}
{{- $component := "simulink" }}
{{- $s := .Values.simulink }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "suite.componentFullname" (dict "Release" .Release "component" $component) }}
  labels:
    {{- include "suite.labels" . | nindent 4 }}
    {{- include "suite.selectorLabels" (dict "ctx" . "component" $component) | nindent 4 }}
spec:
  type: {{ $s.service.type }}
  selector:
    {{- include "suite.selectorLabels" (dict "ctx" . "component" $component) | nindent 4 }}
  ports:
    - name: http
      port: {{ $s.service.port }}
      targetPort: http
{{- end }}
